spring:
  application:
    name: servicio-items
server:
  port: 8002
#Para registrarse en eureka se debe enviar un latido de corazón, si deja de transmitirla por mas
#de 90 segundos se borra
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka